### PR TITLE
fix: return empty array when find yield no results

### PR DESCRIPTION
**Pull request by DxCx**
* When find has no results ObservableCursor will yield no results until first item inserted.
this patch will return empty array in such case (current state) and then wait for new entries.

* Not sure why dist is in git but i kept it that way.

### CODE REVIEW

**Comment by atd** [comment]
Thank you @DxCx I found the same issue

**Comment by DxCx** [comment]
i think CI is broken though.. :\

**Comment by dotansimha** [comment]
@DxCx yeah its a CI issue... looks good.

**Comment by dotansimha** [comment]
Fixed in 0.4.8

**Pull request merged**
