### PR TITLE
Update documentation for MeteorObservable

### PR DESCRIPTION
**Pull request by ijager**
- Update introduction, better flow and improved English.
- Add links to relevant Meteor API docs.
- Update type names.

### CODE REVIEW

**Comment by dotansimha** [comment]
Awesome!! Thanks @ijager .
Our API documentation is generated from the actual code, which means that the source code is in https://github.com/Urigo/meteor-rxjs/blob/master/src/MeteorObservable.ts , any chance you can add your changes there over the actual code, and then I will generate the `.md` file.

**Comment by ijager** [comment]
Oh right, I'll add the changes to the code then later today.

**Comment by ijager** [comment]
updated

**Comment by dotansimha** [comment]
Awesome! I generated the markdown docs (using the command `npm run build`).
Thanks @ijager !

**Pull request merged**
